In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import numpy as np
from sklearn.preprocessing import StandardScaler

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import GRU
from keras.layers import SimpleRNN
from keras.metrics import BinaryAccuracy, CategoricalAccuracy

In [4]:
x = np.load('/content/drive/MyDrive/data.T/X.npy')
y = np.load('/content/drive/MyDrive/data.T/Y.npy')

for i in range(15002):
    scaler = StandardScaler().fit(x[i])
    x[i] = scaler.transform(x[i])

d = np.genfromtxt('/content/drive/MyDrive/data.T/Vert.csv', delimiter = ',')
d = d[1:]

In [6]:
model = Sequential()
model.add(LSTM(5000, return_sequences=True, activation="softmax"))
model.add(Dense(5000))
model.add(Dense(15002, activation = "softmax"))
model.compile(optimizer='Adam', loss = 'categorical_crossentropy', metrics = 'CategoricalAccuracy')

In [35]:
model.fit(x, y, epochs=10, batch_size=32)

Epoch 1/10
469/469 [==============================] - 53s 114ms/step - loss: 1.0157 - categorical_accuracy: 0.8298
Epoch 2/10
469/469 [==============================] - 53s 114ms/step - loss: 0.9604 - categorical_accuracy: 0.8421
Epoch 3/10
469/469 [==============================] - 53s 114ms/step - loss: 0.9051 - categorical_accuracy: 0.8522
Epoch 4/10
469/469 [==============================] - 53s 114ms/step - loss: 0.8544 - categorical_accuracy: 0.8613
Epoch 5/10
469/469 [==============================] - 53s 114ms/step - loss: 0.8062 - categorical_accuracy: 0.8725
Epoch 6/10
469/469 [==============================] - 53s 114ms/step - loss: 0.7576 - categorical_accuracy: 0.8806
Epoch 7/10
469/469 [==============================] - 54s 114ms/step - loss: 0.7122 - categorical_accuracy: 0.8899
Epoch 8/10
469/469 [==============================] - 53s 114ms/step - loss: 0.6707 - categorical_accuracy: 0.8966
Epoch 9/10
469/469 [==============================] - 54s 114ms/step - loss: 0.6

In [8]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_1 (LSTM)               (None, 4, 5000)           106140000 
                                                                 
 dense_2 (Dense)             (None, 4, 5000)           25005000  
                                                                 
 dense_3 (Dense)             (None, 4, 15002)          75025002  
                                                                 
Total params: 206,170,002
Trainable params: 206,170,002
Non-trainable params: 0
_________________________________________________________________


In [36]:
test_x = np.load('/content/drive/MyDrive/data.T/testX.npy')
test_y = np.load('/content/drive/MyDrive/data.T/testY.npy')

In [37]:
for i in range(250):
    scaler = StandardScaler().fit(test_x[i])
    test_x[i] = scaler.transform(test_x[i])

In [38]:
y_pred= model.predict(test_x)

8/8 [==============================] - 0s 23ms/step


In [39]:
err1 = []
err2 = []
for n_dip in range(len(test_y)):
  k1=[]
  k2=[]

  for j in range(4):
    max = y_pred[n_dip][j][0]
    for i in range(15002):
      if y_pred[n_dip][j][i]>max:
        max = y_pred[n_dip][j][i]
        k = i
    k1.append(k)

  for j in range(4):
    max = test_y[n_dip][j][0]
    for i in range(15002):
      if test_y[n_dip][j][i]>max:
        max = test_y[n_dip][j][i]
        k = i
    k2.append(k)
  
  for i in range(4):
    tr = d[k2[i]]
    pr = d[k1[i]]
    err1.append((((tr[0]-pr[0])*1000)**2+((tr[1]-pr[1])*1000)**2+((tr[2]-pr[2])*1000)**2)**(1/2))

  for i in range(3):
    d1 = d[k1[i]]
    d2 = d[k1[i+1]]
    err2.append((((d2[0]-d1[0])*1000)**2+((d2[1]-d1[1])*1000)**2+((d2[2]-d1[2])*1000)**2)**(1/2))

err1 = np.array( err1 )
err2 = np.array( err2 )

print(np.mean(err1))
print(np.mean(err2))

24.49152855395931
37.34228891073179


In [40]:
err_sig = []
for i in range(len(err1)):
  if i % 4 == 0 and i != 0:
    err_sig.append(np.mean(err1[i-4:i]))

In [41]:
err_sig

[10.333728527997183,
 12.126143307132722,
 7.977421779704088,
 31.748329573942655,
 12.596902147603297,
 46.45432740481504,
 14.012977694983793,
 52.37407880343428,
 5.683105422478528,
 63.54637415760174,
 25.150699445395258,
 13.68097623756696,
 7.06965661150779,
 16.679569257558562,
 31.64898375527395,
 50.384510246108725,
 16.721039938305108,
 57.509758441004735,
 6.481587843056225,
 51.42195609853613,
 52.136367420913245,
 20.64442840546345,
 46.16983209594931,
 7.272608192640295,
 72.85810895719183,
 13.255002307264277,
 9.858251014943795,
 16.646859797772763,
 17.992845399713346,
 38.331057416469875,
 25.94931255429983,
 11.468059842369899,
 4.488818026093373,
 8.329442597852223,
 11.7952499745805,
 30.33347492928841,
 11.214946809387232,
 22.344425972366473,
 13.81164292081285,
 38.44546201607441,
 17.65921817182431,
 31.95123281664235,
 9.946027538418079,
 15.776667640123328,
 44.35640710168249,
 9.653944170511522,
 8.975867784990795,
 6.695118407979634,
 40.94091116454451,
 7.

In [42]:
k2

[5911, 6107, 6249, 13484]

In [43]:
k1

[6602, 7002, 6349, 13683]

In [44]:
np.max(y_pred[0][0])

0.54356825

In [ ]:
#model.save('lstm+fc+№2.h5') 

In [45]:
forimage= model.predict(test_x[:1])

1/1 [==============================] - 0s 27ms/step


In [46]:
k1 =[]
dip_y = np.zeros((4,3))
for i in range(4):
    dip_y[i] = d[test_y[0][i].nonzero()[0][0]]
    k1.append(test_y[0][i].nonzero()[0][0])

In [47]:
forimage.shape

(1, 4, 15002)

In [48]:
k2 = []
for j in range(4):
  max = forimage[0][j][0]
  for i in range(15002):
    if forimage[0][j][i]>max:
      max = forimage[0][j][i]
      k = i
  k2.append(k)

dip_test = np.zeros((4,3))
for i in range(len(k2)):
  dip_test[i] = d[k2[i]]

In [49]:
print(k1)
print(k2)

[8512, 8106, 8635, 8440]
[8340, 8106, 8494, 7988]


In [50]:
print(dip_y*1000)
print(dip_test*1000)

[[-40.927 -31.953  81.446]
 [-46.036 -32.946  81.814]
 [-40.678 -29.895  82.077]
 [-41.599 -33.766  83.539]]
[[-43.552 -45.352  86.675]
 [-46.036 -32.946  81.814]
 [-38.431 -34.146  93.196]
 [-51.169 -34.806  94.516]]


In [51]:
err1 = []
for i in range(4):
  tr = d[k2[i]]
  pr = d[k1[i]]
  err1.append((((tr[0]-pr[0])*1000)**2+((tr[1]-pr[1])*1000)**2+((tr[2]-pr[2])*1000)**2)**(1/2))

In [52]:
err1 = np.array(err1)
np.mean(err1)

10.333728527997183